const definition = {
  name: 'Ispitivanje elektroormara Duplico',
  props: { id: 'nkda9a1' },
  // it maybe would've been easier to manipulate sections if it were an object with keys as keys
  sections: [
    {
      key: '7d9sad',
      title: '1. Provjera postavljenih elementa',
      values: [
        [
          '1.1 Svi spojevi i vijci su dobro zategnuti',
          'Ispitati "povlačenjem" žica na spojevima s elementima',
          true,
          false,
          false,
          null,
        ],
        [
          '1.2 Svi elementi van ploče su ugrađeni',
          'Uvodnice, svjetiljka, grijač, oprema na vratima',
          true,
          false,
          false,
          null,
        ],
        [
          '1.3 Ugrađeni elementi odgovaraju popisu elemenata',
          'Detaljan pregled oznaka elementa-kataloška oznaka elementa',
          true,
          false,
          false,
          null,
        ],
        [
          '1.4 Odrađeno je izjednačenje potencijala (PE brika) na sve metalne djelove elektroormara',
          'Pogledati svaku metalnu površinu!!!',
          true,
          false,
          false,
          null,
        ],
        [
          '1.5 Nema oštećenih vodiča ili mogućih oštećenja vodljivih djelova',
          'Otvoriti kanalice i provjeriti',
          true,
          false,
          false,
          null,
        ],
        [
          '1.6 Sve stezaljke su postavljene i označene',
          'Vizualni pregled svih stezaljki',
          true,
          false,
          false,
          null,
        ],
        [
          '1.7 Opisne oznake (na vratima) su zaljepljene prema dokumentaciji',
          'Vizualni pregled tipkala, prekidača i lampica s vanjske strane',
          true,
          false,
          false,
          null,
        ],
        [
          '1.8 Oznake kabela se nalaze u ormaru',
          'Vizualna potvrda (otvoriti kutiju i pogledati)',
          false,
          true,
          false,
          null,
        ],
        [
          '1.9 Postavljene su oznake upozorenja (OPASNOST 400V ILI OPASNOST 230V)',
          'Vizualna potvrda (pogledati na vrata ormara)',
          false,
          true,
          false,
          null,
        ],
      ],
    },
    {
      key: '7d99ad',
      title: '2. Električna ispitivanja',
      values: [
        [
          '2.0 Ormar je ohmski ispitan i ožićenje odgovara shemi ',
          'Odraditi ohmsko ispitivanje ohmmetrom',
          true,
          false,
          false,
          null,
        ],
        [
          '2.1 Ormar je funkcionalno ispitan i radi sukladno dostavljenoj shemi',
          'Ormar spojiti na privremeno napajanje i ispitati njegovu funkcionalnost',
          false,
          true,
          false,
          null,
        ],
        [
          '2.2 Postavke opreme su postavljene prema dokumentaciji',
          'Podešenja motornih zaštitnih sklopki, switchevi na PLC-u',
          false,
          true,
          false,
          null,
        ],
      ],
    },
    {
      key: '7sv39sad',
      title: '3. Vanjski pregled',
      values: [
        [
          '3.1 Sve zaštite od slučajnog dodira su postavljene',
          'Postavljena je zaštita na bakrene sabirnice ili na otvorene spojeve',
          false,
          true,
          false,
          null,
        ],
        [
          '3.2 Ormar je neoštećen, uredan i usisan',
          'Vizualna provjera urednosti ormara',
          true,
          false,
          false,
          null,
        ],
        [
          '3.3 Bočne stranice, krov i ploče za uvod kabela/uvodnice su postavljene',
          'Vizualna provjera montaže mehaničkih elemenata',
          true,
          false,
          false,
          null,
        ],
        [
          '3.4 Dokumentacija za klijenta je postavljena u ormar',
          'Vizualna provjera i potvrda ',
          true,
          false,
          false,
          null,
        ],
        [
          '3.5 Višak opreme i oprema koja se ne ugrađuje u ormar, eventualni mehanički djelovi ormara su u ormaru',
          'Odnosi se na višak isporučene opreme, oprema koja se montira na terenu, podnice, itd. ',
          true,
          false,
          false,
          null,
        ],
      ],
    },
    {
      key: '7s3ubir',
      title: '4. Pregled radne prostorije',
      values: [
        [
          '4.1 Radno mjesto je počišćeno, napravljen je povrat robe i smeće je bačeno',
          'Počistiti radno mjesto, baciti smeće i napraviti povrat preostale robe',
          true,
          false,
          false,
          null,
        ],
      ],
    },
  ],
  headGroups: [null, null, ['Rezultat', 3], null],
  headDefinition: [
    {
      props: { id: '692dsf', title: 'Ispitivanje', editable: false },
      component: 'TextColumn',
    },
    {
      props: { id: '692ds123f', title: 'Način ispitivanja', editable: false },
      component: 'TextColumn',
    },
    {
      props: { id: 'vas0v8', group: 'Result', title: 'Da', editable: true },
      component: 'CheckboxColumn',
    },
    {
      props: { id: '89rwq8', group: 'Result', title: 'Ne', editable: true },
      component: 'CheckboxColumn',
    },
    {
      props: { id: '02eada', group: 'Result', title: 'N/A', editable: true },
      component: 'CheckboxColumn',
    },
    {
      props: { id: '8dsga8', title: 'Komentar', editable: true },
      component: 'TextColumn',
    },
  ],
}
